[platformio]
default_envs = teensy40_height

[env]
platform = teensy
board = teensy40
framework = arduino
monitor_speed = 115200
build_flags =
    -D USB_MIDI_SERIAL
    -D CORE_DEBUG_LEVEL=0

[env:teensy40_basic]
build_flags =
    ${env.build_flags}
    -D ENABLE_HEIGHT_SENSOR=0

[env:teensy40_height]
build_flags =
    ${env.build_flags}
    -D ENABLE_HEIGHT_SENSOR=1
lib_deps =
    https://github.com/pololu/vl53l4cd-arduino.git#1.0.0

[env:native]
platform = native
test_framework = custom
build_src_filter = -<*>
build_flags = -std=c++17
